# version: 0.2

# phases:
#   pre_build:
#     commands:
#       - echo Starting pipeline . . .
#       - wget https://github.com/zricethezav/gitleaks/releases/download/v8.13.0/gitleaks_8.13.0_linux_x64.tar.gz
#       - tar -xzf gitleaks_8.13.0_linux_x64.tar.gz
#       - sudo install gitleaks /usr/bin
#       - echo "Gitleaks installed."

#   build:
#     commands:
#       - echo Build started on `date`
#       - echo Scanning with gitleaks...
#       - git init
#       - gitleaks detect --verbose --source . -f json -r gitleaks.json || true

#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - cat gitleaks.json

# artifacts:
#   files: gitleaks.json
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing source NPM dependencies..."
      - npm install -g retire

  build:
    commands:
      - echo "Build started for ${BUILD_ENV} on $(date)"
      - retire --path . --outputformat json --outputpath retire.json || true
      - echo "retire completed..."

artifacts:
    files: retire.json