version: 0.2

env:
  variables:
    BUCKET_NAME: "demo.web.295devops.com"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing source NPM dependencies..."
      - npm install

  build:
    commands:
      - echo "Build started for ${BUILD_ENV} on $(date)"
      - npm run build
      - echo "Build completed..."

  post_build:
    commands:
      - echo "Post-Build started on $(date)"
      - ls build
      # Uncomment the following line to upload the build to S3
      # - aws s3 cp ./build s3://${BUCKET_NAME} --recursive
      - echo "Post-Build completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
